name:                haskellgram
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/verhovv/haskellgram
license:             BSD3
author:              verhovv&dmitry416
maintainer:          none
copyright:           2024 verhovv&dmitry416
#category:
extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - data-default
  - lens
  - monomer
  - text
  - text-show
  - network
  - bytestring
executables:
  app:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    - -rtsopts 
    - -with-rtsopts=-N